### PR TITLE
dev/core#1399 Fixing 'DB Error: no such field' when doing export with…

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
When doing export with a custom field on address, i get `DB Error: no such field`

Reproduction steps
----------------------------------------
1. Create a custom field on address
1. Search for contacts
1. Action `Export Contact`
1. Use `Select fields for export` and add the custom field on address
1. Click `Continue` -> `DB Error: no such field`

Current behaviour
----------------------------------------
`DB Error: no such field`

The field that doesn't exist is : 
```
`Home-value_validit_de_l_adresse_postale_41`.id as `Home-value_validit_de_l_adresse_postale_41_id`
```

See [dev/core#1399](https://lab.civicrm.org/dev/core/issues/1399) for more details

### CODE REVIEW

**Comment by seamuslee001** [comment]
@samuelsov do you know when this stopped working or did it ever work?

**Comment by samuelsov** [comment]
@seamuslee001 I'm not sure but it seemed to work in 5.14 (no bug reported in 6 months on this site that was doing export on custom address fields)

**Comment by VangelisP** [comment]
@seamuslee001 & @samuelsov fwiw, I believe this issue relates with this: 
https://github.com/civicrm/civicrm-core/pull/15541 (gitlab issue [1324](https://lab.civicrm.org/dev/core/issues/1324))

**Comment by mlutfy** [comment]
@VangelisP Would merging this PR cause a regression with that issue, or do you mean that it's the likely cause of the regression, and this fix seems OK?

**Comment by jitendrapurohit** [comment]
@samuelsov I just tried to replicate this problem in order to review the change. I don't see any db error while exporting the address custom field. Can you retest and confirm if it is still an issue with the updated master version?

**Comment by VangelisP** [comment]
Ok, I totally missed this one @mlutfy & @samuelsov , really sorry about that. 
I can confirm what @jitendrapurohit  says, I cannot replicate the issue. Is it perhaps related with french hyphenation while creating the fields ?

**Comment by samuelsov** [comment]
@jitendrapurohit @VangelisP Well, it seems you are right, I'm able to reproduce in a vanilla site v5.18.2 but not in 5.14, nor 5.20 so it seems to have been solved somehow.

I haven't updated the site where the problem first appeared so there might be a specific problem on this site but i doubt. If necessary i will open a new issue after i do the upgrade.
